# Generated by Django 5.1.15 on 2026-04-28 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "in_progress"),
                            ("x_won", "x_won"),
                            ("o_won", "o_won"),
                            ("draw", "draw"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "player_o",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="games_as_o",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "player_x",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="games_as_x",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="games_won",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Move",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("number", models.PositiveSmallIntegerField()),
                ("mark", models.CharField(choices=[("X", "X"), ("O", "O")], max_length=1)),
                ("row", models.PositiveSmallIntegerField()),
                ("col", models.PositiveSmallIntegerField()),
                ("played_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moves",
                        to="games.game",
                    ),
                ),
                (
                    "played_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.AddConstraint(
            model_name="game",
            constraint=models.CheckConstraint(
                condition=models.Q(("player_x", models.F("player_o")), _negated=True),
                name="game_players_must_differ",
            ),
        ),
        migrations.AddConstraint(
            model_name="move",
            constraint=models.UniqueConstraint(
                fields=("game", "number"), name="unique_move_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="move",
            constraint=models.UniqueConstraint(
                fields=("game", "row", "col"), name="unique_move_cell"
            ),
        ),
    ]
